/*
 * This source file was generated by the Gradle 'init' task
 */
package pt.iscte.errorcompass

import com.github.javaparser.JavaParser
import com.github.javaparser.ParserConfiguration
import com.github.javaparser.ast.CompilationUnit
import com.github.javaparser.symbolsolver.JavaSymbolSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver
import pt.iscte.errorcompass.checkers.*
import pt.iscte.errorcompass.generates.ErrorGenerator
import pt.iscte.errorcompass.model.ResultAnalyzer
import java.io.File
import java.nio.file.Paths


class ErrorCompass() {
    /***
     * Run the evaluate process in a string with JavaCode
     */
    fun run(code: String): Result<ResultAnalyzer> {
        val typeSolver = CombinedTypeSolver()
        typeSolver.add(ReflectionTypeSolver())
        typeSolver.add(JavaParserTypeSolver(Paths.get(".")))
        val symbolSolver = JavaSymbolSolver(typeSolver)
        val parserConfiguration = ParserConfiguration()
        parserConfiguration.setSymbolResolver(symbolSolver)

        val cu: CompilationUnit = JavaParser(parserConfiguration).parse(code.trimIndent()).result.get()
        val variableTypeChecker = VariableTypeChecker(cu)
        val returnTypeChecker = MethodReturnChecker()
        val controlStructureChecker = ControlStructureChecker()
        val stringComparisonChecker = StringComparisonChecker()
        val uninitializedVariableChecker = UninitializedVariableChecker()
        //Execute Checker
        variableTypeChecker.visit(cu, null)
        returnTypeChecker.visit(cu, null)
        controlStructureChecker.visit(cu, null)
        stringComparisonChecker.visit(cu, null)
        uninitializedVariableChecker.visit(cu, null)

        val totalIssues = variableTypeChecker.issues + returnTypeChecker.issues + controlStructureChecker.issues + stringComparisonChecker.issues + uninitializedVariableChecker.issues
        val generator = ErrorGenerator()
        val errors = totalIssues.mapNotNull { generator.generate(it) }
        return Result.success(ResultAnalyzer(errors))
    }

    /***
     * Run the evaluate process in a file or directory
     */
    fun run(file: File): Result<ResultAnalyzer> {
        return Result.success(ResultAnalyzer(emptyList()))
    }
}


