/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import pt.iscte.errorcompass.ErrorCompass

fun main(args: Array<String>) {
    val javaCode = """
        public class Main {
            public static void main(String[] args) {
                int x = "Hello"; // Exemplo de tipo inválido
                String y = 42;   // Exemplo de tipo inválido
                String z = "World";
                int a = 123;
                Main m = new Main("Hello", 42); // Exemplo de tipo inválido
                m.someMethod(y,x);
            }

            public Main(int number, String text) {
                // Construtor
            }

            public void someMethod(int param1, String param2) {
                // Método
            }
        }
    """

    var errorCompasss = ErrorCompass(rulesCustom = emptyList())
    errorCompasss.run(javaCode)
}
